name: Main CI (lint/tests + build/publish)

on:
  workflow_call:
  push:
    branches:
      - master

#  release:
#    types: [published]

  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

jobs:
  install-and-cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: "${{ secrets.COMMIT_KEY }}"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Use get-npm-cache Action
        uses: ./.github/actions/npm-cache

#      - name: Get npm-cache folder
#        id: npm-cache-dir
#        shell: bash
#        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}  # by default, it should be ~/.npm
#
#      - name: Restore npm cache
#        id: npm-cache-restore
#        uses: actions/cache/restore@v4
#        with:
#          path: ${{ steps.npm-cache-dir.outputs.dir }}
#          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - name: Save npm cache
        id: npm-cache-save
        uses: actions/cache/save@v4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  lint-and-test:
    runs-on: ubuntu-latest
    needs: install-and-cache

    steps:
      - uses: actions/checkout@v4

      - name: Use get-npm-cache Action
        uses: ./.github/actions/npm-cache

      - run: npm ci

      - run: npm run lint
      - run: npm run test

  publish:
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      # todo: think, if we can use cache from previous job

      - name: Use get-npm-cache Action
        uses: ./.github/actions/npm-cache

      - run: npm ci
      - run: npm run build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
