name: NPM Publish

on:
  release:
    types:
      - published
      - prereleased
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-snapshot.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use get-npm-cache Action
        uses: ./.github/actions/npm-cache
      - run: npm ci

      - run: npm run test
      - run: npm run build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
